"""Mock event data for development without API keys."""

from datetime import UTC, datetime, timedelta
from decimal import Decimal

from app.ingestion.base import NormalizedEvent


def generate_mock_events(city: str = "Austin") -> list[NormalizedEvent]:
    now = datetime.now(UTC)

    events = [
        NormalizedEvent(
            external_id="mock-001",
            source="mock",
            title="Blues on the Green - Free Concert Series",
            description="Austin's favorite free outdoor concert series returns to Zilker Park.",
            venue_name="Zilker Park",
            venue_address="2100 Barton Springs Rd",
            city=city,
            state="TX",
            latitude=30.2669,
            longitude=-97.7729,
            starts_at=now + timedelta(days=2, hours=18),
            price_min=Decimal("0"),
            price_max=Decimal("0"),
            url="https://example.com/blues-on-the-green",
            image_url="https://placehold.co/600x400?text=Blues+on+the+Green",
            categories=["music", "blues", "outdoor"],
        ),
        NormalizedEvent(
            external_id="mock-002",
            source="mock",
            title="Austin Food & Wine Festival",
            description="Three days of culinary excellence featuring top chefs and winemakers.",
            venue_name="Auditorium Shores",
            venue_address="800 W Riverside Dr",
            city=city,
            state="TX",
            latitude=30.2615,
            longitude=-97.7514,
            starts_at=now + timedelta(days=5, hours=11),
            ends_at=now + timedelta(days=7, hours=22),
            price_min=Decimal("75"),
            price_max=Decimal("250"),
            url="https://example.com/food-wine-fest",
            image_url="https://placehold.co/600x400?text=Food+%26+Wine+Fest",
            categories=["food", "festival"],
        ),
        NormalizedEvent(
            external_id="mock-003",
            source="mock",
            title="Stand-Up Comedy Night with Sarah Johnson",
            description="Netflix special comedian Sarah Johnson brings her national tour to Austin.",
            venue_name="Paramount Theatre",
            venue_address="713 Congress Ave",
            city=city,
            state="TX",
            latitude=30.2700,
            longitude=-97.7411,
            starts_at=now + timedelta(days=1, hours=20),
            on_sale_at=now - timedelta(days=14),
            price_min=Decimal("35"),
            price_max=Decimal("85"),
            url="https://example.com/comedy-sarah-johnson",
            image_url="https://placehold.co/600x400?text=Comedy+Night",
            categories=["comedy", "arts"],
        ),
        NormalizedEvent(
            external_id="mock-004",
            source="mock",
            title="Austin Tech Meetup - AI & Machine Learning",
            description="Monthly meetup for tech enthusiasts. This month: building with LLMs.",
            venue_name="Capital Factory",
            venue_address="701 Brazos St",
            city=city,
            state="TX",
            latitude=30.2686,
            longitude=-97.7405,
            starts_at=now + timedelta(days=3, hours=18, minutes=30),
            price_min=Decimal("0"),
            price_max=Decimal("0"),
            url="https://example.com/tech-meetup",
            image_url="https://placehold.co/600x400?text=Tech+Meetup",
            categories=["technology", "meetup"],
        ),
        NormalizedEvent(
            external_id="mock-005",
            source="mock",
            title="Indie Rock Showcase - 4 Bands, 1 Night",
            description="Featuring local Austin bands: The Velvet Cactus, Desert Moon, Neon Armadillo, and Bluebonnet Highway.",
            venue_name="Mohawk Austin",
            venue_address="912 Red River St",
            city=city,
            state="TX",
            latitude=30.2680,
            longitude=-97.7365,
            starts_at=now + timedelta(hours=6),
            price_min=Decimal("15"),
            price_max=Decimal("25"),
            url="https://example.com/indie-rock-showcase",
            image_url="https://placehold.co/600x400?text=Indie+Rock",
            categories=["music", "rock", "indie"],
        ),
        NormalizedEvent(
            external_id="mock-006",
            source="mock",
            title="Farmers Market & Live Music",
            description="Weekly farmers market with fresh produce, artisan goods, and live acoustic music.",
            venue_name="Mueller Lake Park",
            venue_address="4550 Mueller Blvd",
            city=city,
            state="TX",
            latitude=30.2985,
            longitude=-97.7058,
            starts_at=now + timedelta(days=4, hours=9),
            ends_at=now + timedelta(days=4, hours=13),
            price_min=Decimal("0"),
            price_max=Decimal("0"),
            url="https://example.com/farmers-market",
            image_url="https://placehold.co/600x400?text=Farmers+Market",
            categories=["food", "music", "outdoor", "market"],
        ),
        NormalizedEvent(
            external_id="mock-007",
            source="mock",
            title="Austin FC vs. LA Galaxy",
            description="MLS regular season match at Q2 Stadium.",
            venue_name="Q2 Stadium",
            venue_address="10414 McKalla Pl",
            city=city,
            state="TX",
            latitude=30.3881,
            longitude=-97.7195,
            starts_at=now + timedelta(days=6, hours=19, minutes=30),
            on_sale_at=now - timedelta(days=30),
            price_min=Decimal("40"),
            price_max=Decimal("200"),
            url="https://example.com/austin-fc-galaxy",
            image_url="https://placehold.co/600x400?text=Austin+FC",
            categories=["sports", "soccer"],
        ),
        NormalizedEvent(
            external_id="mock-008",
            source="mock",
            title="Outdoor Yoga in the Park",
            description="Free community yoga session for all levels. Bring your own mat.",
            venue_name="Zilker Botanical Garden",
            venue_address="2220 Barton Springs Rd",
            city=city,
            state="TX",
            latitude=30.2640,
            longitude=-97.7707,
            starts_at=now + timedelta(days=1, hours=7),
            price_min=Decimal("0"),
            price_max=Decimal("0"),
            url="https://example.com/outdoor-yoga",
            image_url="https://placehold.co/600x400?text=Outdoor+Yoga",
            categories=["fitness", "outdoor", "wellness"],
        ),
        NormalizedEvent(
            external_id="mock-009",
            source="mock",
            title="Hamilton - Broadway National Tour",
            description="The blockbuster musical phenomenon comes to Austin's Bass Concert Hall.",
            venue_name="Bass Concert Hall",
            venue_address="2350 Robert Dedman Dr",
            city=city,
            state="TX",
            latitude=30.2849,
            longitude=-97.7316,
            starts_at=now + timedelta(days=10, hours=19),
            on_sale_at=now - timedelta(days=60),
            price_min=Decimal("75"),
            price_max=Decimal("500"),
            url="https://example.com/hamilton-austin",
            image_url="https://placehold.co/600x400?text=Hamilton",
            categories=["arts", "theatre", "musical"],
        ),
        NormalizedEvent(
            external_id="mock-010",
            source="mock",
            title="Craft Beer & BBQ Festival",
            description="Over 50 craft breweries and Austin's best BBQ pitmasters in one place.",
            venue_name="The Long Center Lawn",
            venue_address="701 W Riverside Dr",
            city=city,
            state="TX",
            latitude=30.2594,
            longitude=-97.7505,
            starts_at=now + timedelta(days=8, hours=12),
            ends_at=now + timedelta(days=8, hours=21),
            price_min=Decimal("45"),
            price_max=Decimal("120"),
            url="https://example.com/beer-bbq-fest",
            image_url="https://placehold.co/600x400?text=Beer+%26+BBQ",
            categories=["food", "festival", "outdoor"],
        ),
    ]

    return events
