"""Mock event data for development without API keys."""

from datetime import UTC, datetime, timedelta
from decimal import Decimal

from app.ingestion.base import NormalizedEvent


def generate_mock_events(city: str = "Austin") -> list[NormalizedEvent]:
    now = datetime.now(UTC)

    events = [
        NormalizedEvent(
            external_id="mock-001",
            source="mock",
            title="Blues on the Green - Free Concert Series",
            description="Austin's favorite free outdoor concert series returns to Zilker Park.",
            venue_name="Zilker Park",
            venue_address="2100 Barton Springs Rd",
            city=city,
            state="TX",
            latitude=30.2669,
            longitude=-97.7729,
            starts_at=now + timedelta(days=2, hours=18),
            price_min=Decimal("0"),
            price_max=Decimal("0"),
            url="https://example.com/blues-on-the-green",
            image_url="https://placehold.co/600x400?text=Blues+on+the+Green",
            categories=["music", "blues", "outdoor"],
        ),
        NormalizedEvent(
            external_id="mock-002",
            source="mock",
            title="Austin Food & Wine Festival",
            description="Three days of culinary excellence featuring top chefs and winemakers.",
            venue_name="Auditorium Shores",
            venue_address="800 W Riverside Dr",
            city=city,
            state="TX",
            latitude=30.2615,
            longitude=-97.7514,
            starts_at=now + timedelta(days=5, hours=11),
            ends_at=now + timedelta(days=7, hours=22),
            price_min=Decimal("75"),
            price_max=Decimal("250"),
            url="https://example.com/food-wine-fest",
            image_url="https://placehold.co/600x400?text=Food+%26+Wine+Fest",
            categories=["food", "festival"],
        ),
        NormalizedEvent(
            external_id="mock-003",
            source="mock",
            title="Stand-Up Comedy Night with Sarah Johnson",
            description="Netflix special comedian Sarah Johnson brings her national tour to Austin.",
            venue_name="Paramount Theatre",
            venue_address="713 Congress Ave",
            city=city,
            state="TX",
            latitude=30.2700,
            longitude=-97.7411,
            starts_at=now + timedelta(days=1, hours=20),
            on_sale_at=now - timedelta(days=14),
            price_min=Decimal("35"),
            price_max=Decimal("85"),
            url="https://example.com/comedy-sarah-johnson",
            image_url="https://placehold.co/600x400?text=Comedy+Night",
            categories=["comedy", "arts"],
        ),
        NormalizedEvent(
            external_id="mock-004",
            source="mock",
            title="Austin Tech Meetup - AI & Machine Learning",
            description="Monthly meetup for tech enthusiasts. This month: building with LLMs.",
            venue_name="Capital Factory",
            venue_address="701 Brazos St",
            city=city,
            state="TX",
            latitude=30.2686,
            longitude=-97.7405,
            starts_at=now + timedelta(days=3, hours=18, minutes=30),
            price_min=Decimal("0"),
            price_max=Decimal("0"),
            url="https://example.com/tech-meetup",
            image_url="https://placehold.co/600x400?text=Tech+Meetup",
            categories=["technology", "meetup"],
        ),
        NormalizedEvent(
            external_id="mock-005",
            source="mock",
            title="Indie Rock Showcase - 4 Bands, 1 Night",
            description="Featuring local Austin bands: The Velvet Cactus, Desert Moon, Neon Armadillo, and Bluebonnet Highway.",
            venue_name="Mohawk Austin",
            venue_address="912 Red River St",
            city=city,
            state="TX",
            latitude=30.2680,
            longitude=-97.7365,
            starts_at=now + timedelta(hours=6),
            price_min=Decimal("15"),
            price_max=Decimal("25"),
            url="https://example.com/indie-rock-showcase",
            image_url="https://placehold.co/600x400?text=Indie+Rock",
            categories=["music", "rock", "indie"],
        ),
        NormalizedEvent(
            external_id="mock-006",
            source="mock",
            title="Farmers Market & Live Music",
            description="Weekly farmers market with fresh produce, artisan goods, and live acoustic music.",
            venue_name="Mueller Lake Park",
            venue_address="4550 Mueller Blvd",
            city=city,
            state="TX",
            latitude=30.2985,
            longitude=-97.7058,
            starts_at=now + timedelta(days=4, hours=9),
            ends_at=now + timedelta(days=4, hours=13),
            price_min=Decimal("0"),
            price_max=Decimal("0"),
            url="https://example.com/farmers-market",
            image_url="https://placehold.co/600x400?text=Farmers+Market",
            categories=["food", "music", "outdoor", "market"],
        ),
        NormalizedEvent(
            external_id="mock-007",
            source="mock",
            title="Austin FC vs. LA Galaxy",
            description="MLS regular season match at Q2 Stadium.",
            venue_name="Q2 Stadium",
            venue_address="10414 McKalla Pl",
            city=city,
            state="TX",
            latitude=30.3881,
            longitude=-97.7195,
            starts_at=now + timedelta(days=6, hours=19, minutes=30),
            on_sale_at=now - timedelta(days=30),
            price_min=Decimal("40"),
            price_max=Decimal("200"),
            url="https://example.com/austin-fc-galaxy",
            image_url="https://placehold.co/600x400?text=Austin+FC",
            categories=["sports", "soccer"],
        ),
        NormalizedEvent(
            external_id="mock-008",
            source="mock",
            title="Outdoor Yoga in the Park",
            description="Free community yoga session for all levels. Bring your own mat.",
            venue_name="Zilker Botanical Garden",
            venue_address="2220 Barton Springs Rd",
            city=city,
            state="TX",
            latitude=30.2640,
            longitude=-97.7707,
            starts_at=now + timedelta(days=1, hours=7),
            price_min=Decimal("0"),
            price_max=Decimal("0"),
            url="https://example.com/outdoor-yoga",
            image_url="https://placehold.co/600x400?text=Outdoor+Yoga",
            categories=["fitness", "outdoor", "wellness"],
        ),
        NormalizedEvent(
            external_id="mock-009",
            source="mock",
            title="Hamilton - Broadway National Tour",
            description="The blockbuster musical phenomenon comes to Austin's Bass Concert Hall.",
            venue_name="Bass Concert Hall",
            venue_address="2350 Robert Dedman Dr",
            city=city,
            state="TX",
            latitude=30.2849,
            longitude=-97.7316,
            starts_at=now + timedelta(days=10, hours=19),
            on_sale_at=now - timedelta(days=60),
            price_min=Decimal("75"),
            price_max=Decimal("500"),
            url="https://example.com/hamilton-austin",
            image_url="https://placehold.co/600x400?text=Hamilton",
            categories=["arts", "theatre", "musical"],
        ),
        NormalizedEvent(
            external_id="mock-010",
            source="mock",
            title="Craft Beer & BBQ Festival",
            description="Over 50 craft breweries and Austin's best BBQ pitmasters in one place.",
            venue_name="The Long Center Lawn",
            venue_address="701 W Riverside Dr",
            city=city,
            state="TX",
            latitude=30.2594,
            longitude=-97.7505,
            starts_at=now + timedelta(days=8, hours=12),
            ends_at=now + timedelta(days=8, hours=21),
            price_min=Decimal("45"),
            price_max=Decimal("120"),
            url="https://example.com/beer-bbq-fest",
            image_url="https://placehold.co/600x400?text=Beer+%26+BBQ",
            categories=["food", "festival", "outdoor"],
        ),
        NormalizedEvent(
            external_id="mock-011",
            source="mock",
            title="Austin Comic Con 2026",
            description="Three-day pop culture convention featuring celebrity panels, cosplay contests, artist alley, and exclusive merch. Guests include stars from Marvel, Star Wars, and anime.",
            venue_name="Austin Convention Center",
            venue_address="500 E Cesar Chavez St",
            city=city,
            state="TX",
            latitude=30.2635,
            longitude=-97.7393,
            starts_at=now + timedelta(days=12, hours=10),
            ends_at=now + timedelta(days=14, hours=18),
            on_sale_at=now - timedelta(days=45),
            price_min=Decimal("35"),
            price_max=Decimal("250"),
            url="https://example.com/austin-comic-con",
            image_url="https://placehold.co/600x400?text=Comic+Con",
            categories=["conventions", "entertainment", "family"],
        ),
        NormalizedEvent(
            external_id="mock-012",
            source="mock",
            title="DevOps Days Austin",
            description="Two-day conference for DevOps practitioners. Talks on CI/CD, platform engineering, observability, and cloud-native architecture.",
            venue_name="Hilton Austin",
            venue_address="500 E 4th St",
            city=city,
            state="TX",
            latitude=30.2650,
            longitude=-97.7390,
            starts_at=now + timedelta(days=15, hours=9),
            ends_at=now + timedelta(days=16, hours=17),
            price_min=Decimal("150"),
            price_max=Decimal("400"),
            url="https://example.com/devopsdays-austin",
            image_url="https://placehold.co/600x400?text=DevOps+Days",
            categories=["conventions", "technology", "conference"],
        ),
        NormalizedEvent(
            external_id="mock-013",
            source="mock",
            title="Texas Home & Garden Expo",
            description="Largest home improvement and garden show in Central Texas. Meet contractors, see the latest smart home tech, and shop local artisans.",
            venue_name="Palmer Events Center",
            venue_address="900 Barton Springs Rd",
            city=city,
            state="TX",
            latitude=30.2610,
            longitude=-97.7530,
            starts_at=now + timedelta(days=9, hours=10),
            ends_at=now + timedelta(days=11, hours=17),
            price_min=Decimal("10"),
            price_max=Decimal("25"),
            url="https://example.com/home-garden-expo",
            image_url="https://placehold.co/600x400?text=Home+%26+Garden+Expo",
            categories=["conventions", "expo", "family"],
        ),
        NormalizedEvent(
            external_id="mock-014",
            source="mock",
            title="Beyoncé - Renaissance World Tour",
            description="Global superstar Beyoncé brings her record-breaking tour to Austin.",
            venue_name="Moody Center",
            venue_address="2001 Robert Dedman Dr",
            city=city,
            state="TX",
            latitude=30.2817,
            longitude=-97.7320,
            starts_at=now + timedelta(days=20, hours=20),
            on_sale_at=now - timedelta(days=90),
            price_min=Decimal("95"),
            price_max=Decimal("750"),
            url="https://example.com/beyonce-austin",
            image_url="https://placehold.co/600x400?text=Beyonc%C3%A9",
            categories=["music", "concert", "pop"],
        ),
        NormalizedEvent(
            external_id="mock-015",
            source="mock",
            title="Texas Longhorns vs. Oklahoma Sooners - College Football",
            description="The Red River Rivalry! One of college football's biggest matchups.",
            venue_name="Darrell K Royal-Texas Memorial Stadium",
            venue_address="2139 San Jacinto Blvd",
            city=city,
            state="TX",
            latitude=30.2836,
            longitude=-97.7325,
            starts_at=now + timedelta(days=13, hours=14, minutes=30),
            on_sale_at=now - timedelta(days=60),
            price_min=Decimal("75"),
            price_max=Decimal("500"),
            url="https://example.com/longhorns-sooners",
            image_url="https://placehold.co/600x400?text=Longhorns+Football",
            categories=["sports", "football", "college"],
        ),
        NormalizedEvent(
            external_id="mock-016",
            source="mock",
            title="Saturday Night DJ Set - Rooftop Party",
            description="Top DJs spinning house and techno on the rooftop with skyline views.",
            venue_name="The W Hotel Rooftop",
            venue_address="200 Lavaca St",
            city=city,
            state="TX",
            latitude=30.2650,
            longitude=-97.7467,
            starts_at=now + timedelta(days=2, hours=22),
            price_min=Decimal("20"),
            price_max=Decimal("50"),
            url="https://example.com/rooftop-dj",
            image_url="https://placehold.co/600x400?text=Rooftop+DJ",
            categories=["music", "nightlife", "dj"],
        ),
        NormalizedEvent(
            external_id="mock-017",
            source="mock",
            title="Kids' Science Discovery Day",
            description="Hands-on science experiments, robot demos, and a planetarium show for kids ages 5-12.",
            venue_name="Thinkery Children's Museum",
            venue_address="1830 Simond Ave",
            city=city,
            state="TX",
            latitude=30.2935,
            longitude=-97.7088,
            starts_at=now + timedelta(days=3, hours=10),
            ends_at=now + timedelta(days=3, hours=15),
            price_min=Decimal("12"),
            price_max=Decimal("12"),
            url="https://example.com/kids-science-day",
            image_url="https://placehold.co/600x400?text=Science+Day",
            categories=["family", "education", "kids"],
        ),
    ]

    return events
