"""add_artist_preferences

Revision ID: 4bc359cce68b
Revises: ba945885cdf9
Create Date: 2026-04-06 17:43:39.946087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bc359cce68b'
down_revision: Union[str, None] = 'ba945885cdf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_artist_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('artist_name', sa.String(length=255), nullable=False),
    sa.Column('musicbrainz_id', sa.String(length=100), nullable=True),
    sa.Column('mb_genres', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('genre_context', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_artist_preferences_user_id'), 'user_artist_preferences', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_artist_preferences_user_id'), table_name='user_artist_preferences')
    op.drop_table('user_artist_preferences')
    # ### end Alembic commands ###
